export const zones = [
    { value: 'aba_zone', label: 'ABA ZONE' },
    { value: 'abuja_zone_1', label: 'ABUJA ZONE 1' },
    { value: 'abuja_zone_2', label: 'ABUJA ZONE 2' },
    { value: 'accra_ghana_zone', label: 'ACCRA GHANA ZONE' },
    { value: 'amsterdam_dsp_region', label: 'AMSTERDAM DSP REGION' },
    { value: 'australia_zone', label: 'AUSTRALIA ZONE' },
    { value: 'benin_zone_1', label: 'BENIN ZONE 1' },
    { value: 'benin_zone_2', label: 'BENIN ZONE 2' },
    { value: 'blw_benin_republic', label: 'BLW BENIN REPUBLIC' },
    { value: 'blw_burkina_faso', label: 'BLW BURKINA FASO' },
    { value: 'blw_cameroon_zone', label: 'BLW CAMEROON ZONE' },
    { value: 'blw_cyprus_zone', label: 'BLW CYPRUS ZONE' },
    { value: 'blw_democratic_republic_of_congo', label: 'BLW DEMOCRATIC REPUBLIC OF CONGO' },
    { value: 'blw_ethiopia', label: 'BLW ETHIOPIA' },
    { value: 'blw_ghana_zone_a', label: 'BLW GHANA ZONE A' },
    { value: 'blw_ghana_zone_b', label: 'BLW GHANA ZONE B' },
    { value: 'blw_ghana_zone_c', label: 'BLW GHANA ZONE C' },
    { value: 'blw_ireland', label: 'BLW IRELAND' },
    { value: 'blw_kenya_zone', label: 'BLW KENYA ZONE' },
    { value: 'blw_sa_zone_a', label: 'BLW SA ZONE A' },
    { value: 'blw_sa_zone_b', label: 'BLW SA ZONE B' },
    { value: 'blw_sa_zone_c', label: 'BLW SA ZONE C' },
    { value: 'blw_sa_zone_d', label: 'BLW SA ZONE D (ZIMBABWE-MALAWI-MOZAMBIQUE)' },
    { value: 'blw_sa_zone_e', label: 'BLW SA ZONE E (BOTSWANA-ZAMBIA)' },
    { value: 'blw_sa_new_zealand_pacific_island_zone', label: 'BLW SA, NEW ZEALAND, PACIFIC ISLAND ZONE' },
    { value: 'blw_south_sudan', label: 'BLW SOUTH SUDAN' },
    { value: 'blw_uganda_zone', label: 'BLW UGANDA ZONE' },
    { value: 'blw_uk_subzone_c', label: 'BLW UK SUBZONE C' },
    { value: 'blw_uk_zone_a', label: 'BLW UK ZONE A' },
    { value: 'blw_uk_zone_b', label: 'BLW UK ZONE B' },
    { value: 'blw_usa_region_2', label: 'BLW USA REGION 2' },
    { value: 'blw_wales', label: 'BLW WALES' },
    { value: 'blw_zone_a', label: 'BLW ZONE A' },
    { value: 'blw_zone_b', label: 'BLW ZONE B' },
    { value: 'blw_zone_c_dsp', label: 'BLW ZONE C DSP' },
    { value: 'blw_zone_d', label: 'BLW ZONE D' },
    { value: 'blw_zone_f', label: 'BLW ZONE F' },
    { value: 'blw_zone_h', label: 'BLW ZONE H' },
    { value: 'blw_zone_i', label: 'BLW ZONE I' },
    { value: 'blw_zone_j', label: 'BLW ZONE J' },
    { value: 'blw_zone_k', label: 'BLW ZONE K' },
    { value: 'blw_zone_l', label: 'BLW ZONE L' },
    { value: 'capetown_zone_1', label: 'CAPETOWN ZONE 1' },
    { value: 'capetown_zone_2', label: 'CAPETOWN ZONE 2' },
    { value: 'chad_zone', label: 'CHAD ZONE' },
    { value: 'dallas_zone', label: 'DALLAS ZONE' },
    { value: 'durban_zone', label: 'DURBAN ZONE' },
    { value: 'east_asia_china', label: 'EAST ASIA (CHINA)' },
    { value: 'eastern_europe_region', label: 'EASTERN EUROPE REGION' },
    { value: 'edo_north_central_zone', label: 'EDO NORTH & CENTRAL ZONE' },
    { value: 'ewca_zone_1', label: 'EWCA ZONE 1' },
    { value: 'ewca_zone_2', label: 'EWCA ZONE 2' },
    { value: 'ewca_zone_3', label: 'EWCA ZONE 3' },
    { value: 'ewca_zone_4', label: 'EWCA ZONE 4' },
    { value: 'ewca_zone_5', label: 'EWCA ZONE 5' },
    { value: 'ewca_zone_6', label: 'EWCA ZONE 6' },
    { value: 'gylf', label: 'GYLF' },
    { value: 'ibadan_zone_1', label: 'IBADAN ZONE 1' },
    { value: 'ibadan_zone_2', label: 'IBADAN ZONE 2' },
    { value: 'india_zone', label: 'INDIA ZONE' },
    { value: 'international_missions', label: 'INTERNATIONAL MISSIONS' },
    { value: 'kenya_zone', label: 'KENYA ZONE' },
    { value: 'lagos_subzone_a', label: 'LAGOS SUBZONE A' },
    { value: 'lagos_subzone_b', label: 'LAGOS SUBZONE B' },
    { value: 'lagos_subzone_c', label: 'LAGOS SUBZONE C' },
    { value: 'lagos_virtual_zone', label: 'LAGOS VIRTUAL ZONE' },
    { value: 'lagos_zone_1', label: 'LAGOS ZONE 1' },
    { value: 'lagos_zone_2', label: 'LAGOS ZONE 2' },
    { value: 'lagos_zone_3', label: 'LAGOS ZONE 3' },
    { value: 'lagos_zone_4', label: 'LAGOS ZONE 4' },
    { value: 'lagos_zone_5', label: 'LAGOS ZONE 5' },
    { value: 'lagos_zone_6', label: 'LAGOS ZONE 6' },
    { value: 'loveworld_church_zone', label: 'LOVEWORLD CHURCH ZONE' },
    { value: 'loveworld_global_fellowship', label: 'LOVEWORLD GLOBAL FELLOWSHIP' },
    { value: 'middle_belt_region_zone_1', label: 'MIDDLE BELT REGION ZONE 1' },
    { value: 'middle_belt_region_zone_2', label: 'MIDDLE BELT REGION ZONE 2' },
    { value: 'middle_east_and_south_east_asia_region', label: 'MIDDLE EAST AND SOUTH EAST ASIA REGION' },
    { value: 'midwest_zone', label: 'MIDWEST ZONE' },
    { value: 'ministry_center_abeokuta', label: 'MINISTRY CENTER ABEOKUTA' },
    { value: 'ministry_center_abuja', label: 'MINISTRY CENTER ABUJA' },
    { value: 'ministry_center_calabar', label: 'MINISTRY CENTER CALABAR' },
    { value: 'ministry_center_ibadan', label: 'MINISTRY CENTER IBADAN' },
    { value: 'ministry_center_warri', label: 'MINISTRY CENTER WARRI' },
    { value: 'namibia_group', label: 'NAMIBIA GROUP (NAMIBIA-ANGOLA)' },
    { value: 'nigeria_south_east_zone_1', label: 'NIGERIA SOUTH EAST ZONE 1' },
    { value: 'nigeria_south_east_zone_3', label: 'NIGERIA SOUTH EAST ZONE 3' },
    { value: 'nigeria_south_south_zone_1', label: 'NIGERIA SOUTH SOUTH ZONE 1' },
    { value: 'nigeria_south_south_zone_2', label: 'NIGERIA SOUTH SOUTH ZONE 2' },
    { value: 'nigeria_south_south_zone_3', label: 'NIGERIA SOUTH SOUTH ZONE 3' },
    { value: 'northern_region_1_zone_1', label: 'NORTHERN REGION 1 ZONE 1' },
    { value: 'northern_region_1_zone_2', label: 'NORTHERN REGION 1 ZONE 2' },
    { value: 'northwest_zone_1', label: 'NORTHWEST ZONE 1' },
    { value: 'onitsha_zone', label: 'ONITSHA ZONE' },
    { value: 'ottawa_zone', label: 'OTTAWA ZONE' },
    { value: 'port_harcourt_zone_1', label: 'PORT HARCOURT ZONE 1' },
    { value: 'port_harcourt_zone_2', label: 'PORT HARCOURT ZONE 2' },
    { value: 'port_harcourt_zone_3', label: 'PORT HARCOURT ZONE 3' },
    { value: 'quebec_zone', label: 'QUEBEC ZONE' },
    { value: 'reon', label: 'REON' },
    { value: 'sa_zone_1', label: 'SA ZONE 1' },
    { value: 'sa_zone_2', label: 'SA ZONE 2' },
    { value: 'sa_zone_3', label: 'SA ZONE 3' },
    { value: 'sa_zone_5', label: 'SA ZONE 5' },
    { value: 'southwest_zone_2', label: 'SOUTHWEST ZONE 2' },
    { value: 'southwest_zone_3', label: 'SOUTHWEST ZONE 3' },
    { value: 'southwest_zone_4', label: 'SOUTHWEST ZONE 4' },
    { value: 'southwest_zone_5', label: 'SOUTHWEST ZONE 5' },
    { value: 'tni', label: 'TNI' },
    { value: 'toronto_zone', label: 'TORONTO ZONE' },
    { value: 'uk_zone_1_region_1', label: 'UK ZONE 1 REGION 1' },
    { value: 'uk_zone_1_region_2', label: 'UK ZONE 1 REGION 2' },
    { value: 'uk_zone_2_region_1', label: 'UK ZONE 2 REGION 1' },
    { value: 'uk_zone_3_region_1', label: 'UK ZONE 3 REGION 1' },
    { value: 'uk_zone_3_region_2', label: 'UK ZONE 3 REGION 2' },
    { value: 'uk_zone_4_region_1', label: 'UK ZONE 4 REGION 1' },
    { value: 'uk_zone_4_region_2', label: 'UK ZONE 4 REGION 2' },
    { value: 'usa_region_3', label: 'USA REGION 3' },
    { value: 'usa_zone_1', label: 'USA ZONE 1' },
    { value: 'usa_zone_1_region_1', label: 'USA ZONE 1 REGION 1' },
    { value: 'usa_zone_1_region_2', label: 'USA ZONE 1 REGION 2' },
    { value: 'usa_zone_2_region_1', label: 'USA ZONE 2 REGION 1' },
    { value: 'warri_dsc_subzone', label: 'WARRI DSC SUBZONE' },
    { value: 'western_europe_zone_1', label: 'WESTERN EUROPE ZONE 1' },
    { value: 'western_europe_zone_2', label: 'WESTERN EUROPE ZONE 2' },
    { value: 'western_europe_zone_3', label: 'WESTERN EUROPE ZONE 3' },
    { value: 'western_europe_zone_4', label: 'WESTERN EUROPE ZONE 4' }
];